version: '3'
services:
  narrator-bot:
    image: narrator-bot:latest
    container_name: narrator-bot
    ports: 
      - 8080:8080
    env_file:
      - .env
    networks:
      - private
    depends_on:
      - narrator-postgres
    restart: always
      
    
  narrator-postgres:
    image: postgres:13
    container_name: narrator-postgres
    ports: 
      - 8432:5432
    env_file:
      - .env
    networks:
      - private
    restart: always

networks:
  private: 
    driver: bridge
    